<a href="https://colab.research.google.com/github/uzairname/playing-with-ai/blob/main/basic_speech_transcription.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install git+https://github.com/openai/whisper.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/openai/whisper.git to /tmp/pip-req-build-jrc7rtk5
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git /tmp/pip-req-build-jrc7rtk5
  Resolved https://github.com/openai/whisper.git to commit c09a7ae299c4c34c5839a76380ae407e7d785914
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 22.9 MB/s eta 0:00:00
  Created wheel for openai-whisper: filename=openai_whisper-20230314-py3-none-any.whl size=798038 sha256=b75ee0f05135c7a20107aaa3a5b56ee942558d2f89f2c3450f122eb8628ffdfb
  Stored in directory: /tmp/pip-ephem-wheel-cache-3cpwsf72/wheels/fe/03/29/e7919208d11b4ab32972cb448bb84a9a675d92cd52c9a48341
Successfully built openai-whisper


In [ ]:
import whisper

whisper.available_models()
model = whisper.load_model("tiny.en")
txt = model.transcribe("ATL_se0_ag1_f_03_1.wav")



In [ ]:
txt

{'text': " Can I get your full name please? Okay, and What is your ethnicity? Black. Okay, cool What's your year of birth? 1993 Okay, and hometown where you coming from? Book me a lot. Okay, cool How many lives of Moo-Moo-Moo-Moo? How many years have you lived in a land of area? Like eight is a monster Okay, okay, that was cool. All right. Um Any other places you lived? Just Brooklyn and here Okay, cool cool. What's um like your highest form of education? High school. Cool. Cool Occupation current happy occupation. I'm a school teacher What about your parents birthplace? One is saying Vincent Let's see and what was their occupation and stuff? My mom used to be a school teacher and then when she came to the state she became a RN and my dad He did he played soccer and he Is it a seamstress when you're a guy? Well, he he was a seamstress and then when he came to the states he did like um custodial work Okay, cool cool What'd you do last night? I went out To a white party This is all white

In [ ]:
import wave
import numpy as np

wave


import wave

chunk_size = 44100*200

txts = []

with wave.open('ATL_se0_ag1_f_03_1.wav', 'rb') as wave_file:
    frame_rate = wave_file.getframerate()
    n_frames = wave_file.getnframes()

    for i in range(0, n_frames, chunk_size):
        wave_file.setpos(i)
        chunk_data = wave_file.readframes(chunk_size)

        np_data = np.frombuffer(chunk_data, dtype=np.int16)





[27 31 27 ... -2 -2  0]
[   4    1    3 ... -785 -812 -837]
[-841 -838 -793 ... 1169  946  747]
[562 375 215 ... -84 -52  -6]
[ 27  55  71 ... -84 -85 -57]
[ -5  39  75 ... -47 -18 -33]
[ -50  -55  -27 ... 1989 2134 2266]
[2372 2463 2523 ...   40   62   84]
[ 100  108  106 ... -145 -146 -145]
[-148 -143 -134 ...   32   31   28]


30.146666666666665

In [ ]:
txt["text"]

" Can I get your full name please? Okay, and What is your ethnicity? Black. Okay, cool What's your year of birth? 1993 Okay, and hometown where you coming from? Book me a lot. Okay, cool How many lives of Moo-Moo-Moo-Moo? How many years have you lived in a land of area? Like eight is a monster Okay, okay, that was cool. All right. Um Any other places you lived? Just Brooklyn and here Okay, cool cool. What's um like your highest form of education? High school. Cool. Cool Occupation current happy occupation. I'm a school teacher What about your parents birthplace? One is saying Vincent Let's see and what was their occupation and stuff? My mom used to be a school teacher and then when she came to the state she became a RN and my dad He did he played soccer and he Is it a seamstress when you're a guy? Well, he he was a seamstress and then when he came to the states he did like um custodial work Okay, cool cool What'd you do last night? I went out To a white party This is all white people t